springdoc:
  version: 0.0.1
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: false
    swagger-ui.display-query-params-without-oauth2: true
  paths-to-match:
    - /api/**
