spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://crackerbook-dev.cyzqbwenql3o.ap-northeast-2.rds.amazonaws.com/crackerbook
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: update

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

springdoc:
  version: 0.0.1
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: false
    display-query-params-without-oauth2: true
  paths-to-match:
    - /api/**

frontend:
  # domain: http://localhost:3000
  domain: https://develop.d2tw5qtwawbqat.amplifyapp.com

kakao:
  client-id: 9f0d8ad0bfd2b1e186218619a5ef9d87
  redirect-uri: /callback/kakao
